---
title: "Plotting info curves"
author: "Josef Klafka"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(here)
require(tidyboot)
require(feather)

knitr::opts_chunk$set(echo = TRUE)
```

```{r info curve plotting}
bootstraps <- read_csv(here("Data/CHILDES/curve_bootstraps.csv"))

bootstraps %>%
  filter(length == 8) %>%
  ggplot(aes(x = position, y = empirical_stat, color = speaker)) + 
    geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) + 
    geom_line() + 
    facet_wrap(~language) + 
    scale_x_continuous(breaks = 1:8) + 
    scale_color_manual(values = c("#E69F00", "#56B4E9")) + 
    xlab("Position of predicted word") + 
    ylab("Mean information")
```

Below is the process by which we create the bootstrapped mean information curves across ngram positions.


```{r put unigrams and trigrams together}
# put together old unigrams and new (smoothed) trigrams
childes_trigrams <- read_csv(here("Data/CHILDES/trigram_bootstraps.csv"))
childes_results <- read_feather(here("Data/Paper/all_childes_bootstrap.feather"))

all_childes <- childes_results %>% 
  filter(context == 0) %>% 
  rename(position = word_order) %>%
  mutate(gram = "Unigram", language = recode(language, "Mandarin" = "Chinese")) %>% 
  select(-context) %>% 
  bind_rows(
    childes_trigrams %>% mutate(gram = "Trigram", speaker = recode(speaker, "Adult" = "Parent"))
    )

# now for BNC
bnc_trigrams <- read_csv(here("Data/corpus/bnc_bootstraps.csv"))
bnc_results <- read_feather(here("Data/Paper/bnc_bootstrap.feather"))

all_bnc <- bnc_results %>% 
  filter(context == 0) %>% 
  rename(position = word_order) %>%
  mutate(gram = "Unigram") %>% 
  select(-context, -corpus) %>% 
  bind_rows(
    bnc_trigrams %>% mutate(gram = "Trigram")
    )
```

```{r read data and bootstrap}
childes_results <- read_feather(here("Data/CHILDES/trigram_results.feather"))

# nest the surprisals for serial bootstrapping
nest_d <- childes_results %>% 
  group_by(language, speaker, length, position) %>% 
  nest() %>%
  filter(length %in% 3:9) %>%
  ungroup()

# non-parametic bootstrap for surprisals within language, speaker, length and position
bootstraps <- nest_d %>% 
  mutate(surprisal = map(data, ~tidyboot_mean(.x, surprisal, nboot = 100))) %>%
  select(-data) %>%
  unnest()

bootstraps %>% 
  write_csv(here("Data/CHILDES/trigram_bootstraps.feather"))
```

```{r get results, eval=F, include=F}
## pull together all results from target languages and knit into one feather
langs <- "Eng-NA" # c("Chinese", "French", "German", "Spanish", "Japanese", "Eng-NA")
output_name <- "trigram_results" # use this to name the combined file

get_childes_results <- function(lang) {
  read_csv(here(paste0("Data/", lang, "_adult_results.csv"))) %>%
    mutate(speaker = "Adult") %>%
    bind_rows(
      read_csv(here(paste0("Data/", lang, "_child_results.csv"))) %>%
        mutate(speaker = "Child")
    ) %>%
    mutate(language = lang)
}

childes_results <- map_dfr(langs, ~get_childes_results(.))

childes_results %>% 
  write_feather(here(paste0("Data/CHILDES/", output_name, ".feather")))
```