---
title: "Plotting results"
author: "Josef Klafka and Daniel Yurovsky"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
require(tidyverse)
require(here)
require(feather)

knitr::opts_chunk$set(echo = TRUE)
```

```{r reading and plotting results from kenlm}
results <- read_csv(here("Data/Spanish_results.csv"), col_names = F) %>%
  rename(gram_position = X1, s = X2, length = X3) %>%
  mutate(gram_position = gram_position + 1) # python is zero-indexed

#plotting 
results %>%
  filter(length %in% 5:10) %>% 
  ggplot(aes(x = gram_position, y = s)) + 
    geom_point() + 
    geom_line() + 
    scale_x_continuous(breaks = 1:10) + 
    facet_wrap(~length)
```

```{r storing results}
results %>% 
  mutate(language = "English", speaker = "Parent") %>% 
  write_feather(here("Data/parent_results.feather"))
```

```{r testing Julia}
require(lme4)
require(jglmm)

cbpp <- mutate(cbpp, prop = incidence / size)
gm <- jglmm(prop ~ period + (1 | herd), data = cbpp, family = "binomial",
            weights = cbpp$size)
```