---
title: Wikipedia Surprisal estimation
author: Josef Klafka and Dan Yurovsky
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: show 
---

```{r setup, include=FALSE}
# load packages
library(knitr)
library(here)
library(broom)
library(janitor)
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = FALSE, tidy = FALSE)

theme_set(theme_classic(base_size = 16))
```

helpers
```{r}
get_quantiles <- function(df, num_sections) {
  df %>%
    pull(position) %>%
    quantile(., probs = seq(0, 1, 1/num_sections)) %>%
    round() %>%
    enframe(name = NULL) %>%
    rename(position = value) %>%
    mutate(quantile = 1:(num_sections + 1))
}


relative_slopes <- function(lang_df, pos_list) {

  divides <- pos_list %>%
    group_by(length) %>%
    mutate(start_pos = position, end_pos = lead(position)) %>%
    filter(!is.na(end_pos)) %>%
    group_by(length, quantile) %>%
    nest() %>%
    mutate(position = map(data, ~seq(.x$start_pos, .x$end_pos) %>% 
                            enframe(name = NULL, value = "position"))) %>%
    select(-data) %>%
    unnest(cols = position)
  
  quantile_groups <- divides %>%
    left_join(lang_df, by = c("length", "position")) %>%
    group_by(quantile, length) %>%
    mutate(position = 1:n()) %>%
    group_by(quantile) %>%
    nest() 
  
  quantile_groups %>%
    mutate(slope = map(data, ~lm(surprisal ~ length + I(length^2) +
                                   position, data  = .))) %>%
    mutate(slope = map(slope, tidy)) %>%
    select(-data) %>%
    unnest(cols = slope) %>%
    filter(term == "position") %>%
    select(-term) %>%
    clean_names()
}
```

read data
```{r}
NUM_SECTIONS <- 5

alemanic <- read_csv(here("Data/wikipedia_Alemannic.csv"), 
                     col_names = c("position", "surprisal", "length")) %>%
  mutate(position = position + 1) %>%
  filter(length >= 9, length <= 50)

pos_list <- alemanic %>%
  group_by(length) %>%
  nest() %>%
  mutate(quantiles = map(data, ~get_quantiles(.x, NUM_SECTIONS))) %>%
  select(-data) %>%
  unnest(cols = c(quantiles))

slopes <- relative_slopes(alemanic, pos_list)
```

```{r}
ggplot(slopes, aes(x = quantile, y = estimate)) + 
  geom_pointrange(aes(ymin = estimate - 1.96 * std_error, 
                      ymax = estimate + 1.96 * std_error )) + 
  geom_line()
```
